services:
  - type: web
    name: music-store
    env: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py migrate django_celery_results --noinput
      python manage.py migrate django_celery_beat --noinput
      python manage.py collectstatic --noinput
    startCommand: celery -A music_store worker -l info --concurrency=1 --prefetch-multiplier=1 --max-tasks-per-child=1 --pool=solo

    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: music_store.settings
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        value: django-db
      # Ajoute ici tes variables AWS / Stripe / Backblaze

  - type: worker
    name: music-store-worker
    env: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: celery -A music_store worker -l info --concurrency=1

  - type: worker
    name: music-store-beat
    env: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: celery -A music_store beat -l info

databases:
  - name: music_store_db
    plan: free
    engine: postgres
    version: 15
