services:
  - type: web
    name: music-store
    env: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py migrate django_celery_results --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn music_store.wsgi:application --log-file -

    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: music_store.settings
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        value: django-db
      # AWS / Stripe variables idem...

  - type: worker
    name: music-store-worker
    env: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: celery -A music_store worker -l info

  - type: worker
    name: music-store-beat
    env: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: celery -A music_store beat -l info

databases:
  - name: music_store_db
    plan: free
    engine: postgres
    version: 15
